names = ["yinka", "dammy", "ibukun", "femi", "bisi"]
print(names)
names.sort()
print(names)
names.sort(reverse=True)
print(names)
names.insert(4, "diran")
print(names)
names.append("tosin")
print(names)
